name: MigrateCI
on: push

jobs:
  
  migrate:
     runs-on: ubuntu-latest
     steps:
       - name: checkout the code
         uses: actions/checkout@v4
       - name: Set up JDK 11 for x64
         uses: actions/setup-java@v4
         with:
            java-version: '11'
            distribution: 'temurin'
            architecture: x64
       - name: Run the mavel comments
         run: mvn -s .ci/settings.xml clean verify